### ISSUE TITLE
Tests can't run

### ISSUE THREAD

**Issue by djshapiro** [srn/react-webpack-boilerplate#10]
I cloned your repo, `npm install`ed, and tried `npm test`. I got the error below.

![screen shot 2015-11-19 at 4 43 44 pm](https://cloud.githubusercontent.com/assets/2005881/11285293/bba337f8-8edc-11e5-8baa-33bfc642656b.png)

**Comment by srn** [comment]
The repo has been updated to babel 6 and all dependencies has been updated so this is now obsolete. Let me know if it's still not working though.
