### ISSUE TITLE
Errors when npm start

### ISSUE THREAD

**Issue by smilyanp** [srn/react-webpack-boilerplate#13]
I've cloned the repo and installed it as per the instructions. When I ran "npm start" there were errors in the terminal related to my version of Node and npm. I updated both and repeated the process, but the errors persisted.

Please see the debug file with the errors log attached.

**Comment by srn** [comment]
I don't see any debug file attached?

Here's my output:

```
❯ node -v
v5.6.0

react-webpack-boilerplate master
❯ npm -v
3.7.2

react-webpack-boilerplate master
❯ npm start

> react-webpack-boilerplate@2.0.0 start react-webpack-boilerplate
> node index

server running at localhost:3001, go refresh and see magic
webpack dev server listening on localhost:3000
webpack: bundle is now VALID.
```

Everything is working fine.

**Comment by Squidies** [comment]
If you're running on Windows, try changing line 10 of package.json from

`"dist": "NODE_ENV=production webpack -p --progress",`

to

`"dist": "SET NODE_ENV=production webpack -p --progress",`

I ran a similar error when trying to install on Windows 7.

**Comment by srn** [comment]
All should be good after https://github.com/srn/react-webpack-boilerplate/commit/807fea8b53b16a2cde62d676d0386e18be43751a
