### ISSUE TITLE
package.json -> dist command fails on windows

### ISSUE THREAD

**Issue by EtaiG** [srn/react-webpack-boilerplate#9]
you have:
    "dist": "NODE_ENV=production webpack -p",

But in windows this fails for a cmd script, and needs to be 
    "dist": "SET NODE_ENV=production webpack -p",

Not sure you can do this conditionally there, but you can probably just run a node script which sets the var

**Comment by srn** [comment]
Not sure what the best solution for this is. Maybe remove `NODE_ENV=production` entirely from `package.json` and let the user set it when running `npm run dist`? What do you think?

**Comment by damoberg** [comment]
The [cross-env npm package](https://www.npmjs.com/package/cross-env) solves this environment issue quite nicely.
